
package view;

// <editor-fold defaultstate="collapsed" desc="imports">

import controller.componentes.Paneles;
import java.awt.Dimension;
import static view.MenuPrincipal.escritorio;

// </editor-fold>

/**FORMULARIO DE PRODUCCION.
 * Formulario para la revision y control de la produccion realizada.
 * Contexto de Inventario.
 * @author Miguel
 consigna tu nombre si compartes la autoría de este documento*/
public class GestionProduccion extends Paneles.VentanaInterna {

    /**NOMBRE ARCHIVO IMAGEN DE FONDO PARA ESTA VENTANA. Solo nombre sin extension (obligatorio archivos png)*/
    private static final String NOMBRE_MI_IMAGEN_FONDO = "fondo_productos";
    /***/
    
    /***/
    public GestionProduccion() {
        super(NOMBRE_MI_IMAGEN_FONDO);
        initComponents();
        this.title = "Produccion y Gestion de Productos";
        this.closable = true;
        this.iconable = true;
        Dimension tamaño_escritorio = escritorio.getSize(), mySpc = this.getSize();
        this.setLocation((tamaño_escritorio.width / 8), ((tamaño_escritorio.height - mySpc.height) / 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
