
                        // SENA BRETAÑA CALI //

package RecursosTemporales;

import Modelo.ClasePrincipal;

import Controlador.CtrData;
import Modelo.MdlData;
import Controlador.Fechas;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.*;
import java.awt.event.KeyEvent;
//import java.awt.event.KeyListener;
//import java.awt.event.*;

/**
 * creation: 19/11/2014, 09:31:49 AM
 * author  : Aprendiz
 */
public class InterfazPOS extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    String mitabla = "productos";
    String micampo = "codpro";
    String campcliente;
    DefaultTableModel dtm = new DefaultTableModel();
    Object obs = "";// objeto de busqueda
    double neto;
    String añadir;
    
    ArrayList<Object> add = new ArrayList<>();
    int fila = 0;
    int col = 0;
    Fechas fecha = new Fechas();
    //KeyListener listen = new KeyListener();

    /** Creates new form InterfazPOS */
    public InterfazPOS() {
        initComponents();
        setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        //--
        CtrData data = new CtrData("ventas");
        MdlData exe = new MdlData();
//                                  -->
        exe.Search(data.ExtractAll());
        int nofct = exe.getNumRegs();
        
        //--
        String headers[] = {"Codigo","Cantidad","Descripcion","Valor Und","Total"};
        dtm.setColumnIdentifiers(headers);
        tblcnst.setModel(dtm);
        //--
        txtfch.setText(""+fecha.getDate());
        txtcajero.setText("");
        nofct = nofct+1;
        txtnfact.setText(""+nofct);
        //--
        
        //--
    }

    /*
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        opcioncampobusqueda_ = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtnfact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdescprod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcnst = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcuenta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtneto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcajero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfch = new javax.swing.JTextField();
        Añadir_ = new javax.swing.JButton();
        Salir_ = new javax.swing.JButton();
        Cuadrar_ = new javax.swing.JButton();
        Facturar_ = new javax.swing.JButton();
        Buscar_ = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        Quitar_ = new javax.swing.JButton();
        Retraer_ = new javax.swing.JButton();
        txtcodpro = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        opccliente = new javax.swing.JRadioButton();
        opcprod = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jButton6.setText("jButton2");

        jButton7.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(51, 204, 0));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("No. Factura");

        jLabel3.setBackground(new java.awt.Color(51, 204, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel4.setBackground(new java.awt.Color(51, 204, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Item Actual");

        tblcnst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblcnst.getTableHeader().setReorderingAllowed(false);
        tblcnst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcnstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcnst);

        txtcuenta.setEditable(false);
        txtcuenta.setColumns(1);
        txtcuenta.setFont(new java.awt.Font("Poor Richard", 0, 44)); // NOI18N
        txtcuenta.setRows(1);
        jScrollPane2.setViewportView(txtcuenta);

        jLabel5.setBackground(new java.awt.Color(51, 204, 0));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Producto");

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad");

        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        txtcant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 204, 0));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Total Compra");

        jLabel8.setBackground(new java.awt.Color(51, 204, 0));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Neto");

        jLabel9.setBackground(new java.awt.Color(51, 204, 0));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Cajero");

        txtcajero.setEditable(false);
        txtcajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcajeroActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 204, 0));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("IVA");

        jLabel11.setBackground(new java.awt.Color(51, 204, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Fecha");

        txtfch.setEditable(false);

        Añadir_.setText("AÑADIR");
        Añadir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir_ActionPerformed(evt);
            }
        });

        Salir_.setText("SALIR");
        Salir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_ActionPerformed(evt);
            }
        });

        Cuadrar_.setText("CIERRE");

        Facturar_.setText("FACTURAR");
        Facturar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturar_ActionPerformed(evt);
            }
        });

        Buscar_.setText("BUSCAR");
        Buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ActionPerformed(evt);
            }
        });

        Quitar_.setText("QUITAR");
        Quitar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitar_ActionPerformed(evt);
            }
        });

        Retraer_.setText("DESHACER");

        txtcodpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodproActionPerformed(evt);
            }
        });
        txtcodpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodproKeyTyped(evt);
            }
        });

        opcioncampobusqueda_.add(opccliente);
        opccliente.setText("Cliente");

        opcioncampobusqueda_.add(opcprod);
        opcprod.setText("Producto");
        opcprod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcprodItemStateChanged(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LogoTienda.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(Añadir_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quitar_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcprod)
                                        .addGap(18, 18, 18)
                                        .addComponent(opccliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtdescprod, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Retraer_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Salir_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Facturar_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Cuadrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtneto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdescprod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opcprod)
                            .addComponent(opccliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtfch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Facturar_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cuadrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Retraer_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salir_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Añadir_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quitar_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtneto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void BorrarTabla(){
        for( int i = 1; i <= tblcnst.getRowCount(); i++ ){
            dtm.removeRow(i);
        }
    }


    private void tblcnstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcnstMouseClicked
        // TODO add your handling code here:

        fila = tblcnst.rowAtPoint(evt.getPoint());
        col = tblcnst.columnAtPoint(evt.getPoint());
        if( fila > -1 && col > -1 ){
            this.obs = dtm.getValueAt(fila, 0);
            txtcodpro.setText(""+obs);
        }

    }//GEN-LAST:event_tblcnstMouseClicked

    private void txtcodproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodproKeyTyped
        // TODO add your handling code here:

        char typ = evt.getKeyChar();

        if( ( typ<'0' || typ>'9' ) ){
            evt.consume();
        }


        if( typ == KeyEvent.VK_ENTER ){

            //if( "".equals( txtsearch.getText() ) ){
                this.obs = txtcodpro.getText();
            //}else{
                //this.obs = txtsearch.getText();
            //}

            CtrData data = new CtrData(mitabla);
            MdlData exe = new MdlData();

            try{
                exe.Search(data.ExtWhere( "codpro", ""+obs ) );

                ArrayList<Object> cap = new ArrayList<>();

                if(!exe.getResults().isEmpty()){
                    this.add = exe.getResults();
                    cap.add(add.get(0));
                    cap.add("");
                    cap.add(add.get(2));
                    cap.add(add.get(6));
                    cap.add(0);
                    dtm.addRow(cap.toArray());
                    fila = tblcnst.getRowCount()-1;
                }

                txtdescprod.setText(""+add.get(2));
                //txtcuenta.setText(""+add.get(6));

                //JOptionPane.showMessageDialog(rootPane, "evento enter");
                txtcodpro.setText(""); 
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getMessage(), "POS Nuevo Producto",0);
            }
            this.añadir = "codpro";
        }

    }//GEN-LAST:event_txtcodproKeyTyped

    private void txtcantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantKeyTyped
        // TODO add your handling code here:

        char typ = evt.getKeyChar();
        double cuenta = 0;

        if( ( typ<'0' || typ>'9' ) ){
            evt.consume();
        }

        if( typ == KeyEvent.VK_ENTER ){

            try{

            int c = Integer.parseInt ( txtcant.getText() );

            double total = c * Double.parseDouble( ""+dtm.getValueAt(fila, 3) );//""+add.get(6)

            dtm.setValueAt( ""+total, fila, 4 );
            dtm.setValueAt( ""+c, fila, 1 );
            
            for( int i = 0; i<tblcnst.getRowCount(); i++ ){
                cuenta = cuenta + Double.parseDouble(""+dtm.getValueAt(i, 4));
            }
            
            txtcuenta.setText( ""+cuenta );

            
            //exe = null;
            //data = null;
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, ""+ex.getMessage(), "Cuantos?", 0);
            }
            this.añadir = "cant";
        }

    }//GEN-LAST:event_txtcantKeyTyped

    private void Salir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_ActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_Salir_ActionPerformed

    private void Buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ActionPerformed
        // TODO add your handling code here:

        //if( "".equals( txtsearch.getText() ) ){
          //  this.obs = txtcodpro.getText();
        //}else{
            //this.obs = txtsearch.getText();
       // }
        
        String srch = txtsearch.getText();
        //String cmp = null;
        //String tabla = null;
        
                //CtrData data = new CtrData(tabla);
                //MdlData exe = new MdlData();
        
            try{
                
                if( opcprod.isSelected() ){
                    //tabla = mitabla;
                    //cmp = "codpro";
                    
                CtrData data = new CtrData(mitabla);
                MdlData exe = new MdlData();
                    
                exe.Search(data.ExtWhere( micampo, ""+srch ) );

                if(!exe.getResults().isEmpty()){
                    txtdescprod.setText(""+exe.getResults().get(2));
                    txtcodpro.setText(""+exe.getResults().get(0)); 
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "el producto no existe", "POS Buscar",0);
                }
                
                }
                
                if( opccliente.isSelected() ){
                    //tabla = "clientes";
                    //cmp = "idclientes";
                    
                CtrData data = new CtrData("clientes");
                MdlData exe = new MdlData();
                    
                exe.Search(data.ExtWhere( "idcliente", ""+srch ) );

                if(!exe.getResults().isEmpty()){
                    txtcliente.setText(""+exe.getResults().get(2));
                    //txtcodpro.setText(""+add.get(0)); 
                }
                /*else{
                    JOptionPane.showMessageDialog(rootPane, "el cliente no existe", "POS Buscar",0);
                }*/
                   
                }
                
  
            }   
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getMessage(), "POS Busqueda",0);
            }

    }//GEN-LAST:event_Buscar_ActionPerformed

    @SuppressWarnings("fallthrough")
    private void Añadir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir_ActionPerformed
        // TODO add your handling code here:
        
            if( !txtcodpro.getText().equals("") ) {
            
                this.obs = txtcodpro.getText();

                CtrData data = new CtrData(mitabla);
                MdlData exe = new MdlData();

                try{
                    exe.Search(data.ExtWhere( micampo, ""+obs ) );

                    ArrayList<Object> cap = new ArrayList<>();

                    if(!exe.getResults().isEmpty()){
                        this.add = exe.getResults();
                        cap.add(add.get(0));
                        cap.add("");
                        cap.add(add.get(2));
                        cap.add(add.get(6));
                        cap.add(0);
                        dtm.addRow(cap.toArray());
                        fila = tblcnst.getRowCount()-1;
                    }

                    txtdescprod.setText(""+add.get(2));
                    //txtcuenta.setText(""+add.get(6));
                    txtcodpro.setText("");
                    //JOptionPane.showMessageDialog(rootPane, "evento enter");
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getMessage(), "POS Nuevo Producto",0);
                }

            }
            
            if ( (!txtcant.getText().equals("")) && txtcodpro.getText().equals("") ) {
                
                try{
                    double cuenta = 0;

                    int c = Integer.parseInt ( txtcant.getText() );

                    double total = c * Double.parseDouble( ""+dtm.getValueAt(fila, 3) );//""+add.get(6)

                    dtm.setValueAt( ""+total, fila, 4 );
                    dtm.setValueAt( ""+c, fila, 1 );

                    for( int i = 0; i<tblcnst.getRowCount(); i++ ){
                        cuenta = cuenta + Double.parseDouble(""+dtm.getValueAt(i, 4));
                    }

                    txtcuenta.setText( ""+cuenta );

                    //exe = null;
                    //data = null;
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(rootPane, ""+ex.getMessage(), "Cuantos?", 0);
                }
            }
            
            if( ( !txtcodpro.getText().equals("") ) && ( !txtcant.getText().equals("") ) ){
                
                this.obs = txtcodpro.getText();

                CtrData data = new CtrData(mitabla);
                MdlData exe = new MdlData();

                try{
                    exe.Search(data.ExtWhere( micampo, ""+obs ) );

                    ArrayList<Object> cap = new ArrayList<>();

                    if(!exe.getResults().isEmpty()){
                        this.add = exe.getResults();
                        cap.add(add.get(0));
                        cap.add("");
                        cap.add(add.get(2));
                        cap.add(add.get(6));
                        cap.add(0);
                        dtm.addRow(cap.toArray());
                        fila = tblcnst.getRowCount()-1;
                    }

                    txtdescprod.setText(""+add.get(2));
                    //txtcuenta.setText(""+add.get(6));
                    txtcodpro.setText("");
                    //JOptionPane.showMessageDialog(rootPane, "evento enter");
                    
                    double cuenta = 0;

                    int c = Integer.parseInt ( txtcant.getText() );

                    double total = c * Double.parseDouble( ""+dtm.getValueAt(fila, 3) );//""+add.get(6)

                    dtm.setValueAt( ""+total, fila, 4 );
                    dtm.setValueAt( ""+c, fila, 1 );

                    for( int i = 0; i<tblcnst.getRowCount(); i++ ){
                        cuenta = cuenta + Double.parseDouble(""+dtm.getValueAt(i, 4));
                    }

                    txtcuenta.setText( ""+cuenta );
                    
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getMessage(), "POS Nuevo Producto",0);
                }
                
            }
            
    }//GEN-LAST:event_Añadir_ActionPerformed

    private void Quitar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitar_ActionPerformed
        // TODO add your handling code here:
        
        double cuenta = Double.parseDouble(txtcuenta.getText());
        double rest = Double.parseDouble(""+dtm.getValueAt(fila, 4));
        dtm.removeRow(fila);
        
        cuenta = cuenta - rest;
        
        txtcuenta.setText(""+cuenta);
                
        
        
    }//GEN-LAST:event_Quitar_ActionPerformed

    private void Facturar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturar_ActionPerformed
        // TODO add your handling code here:
        
        
        MdlData exe = new MdlData();
        CtrData data = new CtrData("ventas");
        ArrayList<Object> newsale = new ArrayList<>();
        ArrayList<Object> prods = new ArrayList<>();
        String strprods = "";
        Object[] cods = {};
        
        //String[] prods;
        int cant = 0 ;
        double parcial;
        double total;
        double iva = 0.16;
        double tiva;
        int i = 0;
        //int y = 0;
        
        try{
            
           /* txtcodpro.setText(""+tblcnst.getRowCount());*/
            
            do{ 
                //cods[i] = dtm.getValueAt( i, 0 );
                prods.add("Producto:"+dtm.getValueAt( i, 0 )+", cantidad:"+dtm.getValueAt( i, 1 )+";\n");
                i = i+1;
            }while( i<tblcnst.getRowCount() );
        
        Iterator<Object> exp = prods.iterator();
        while ( exp.hasNext() ){
            strprods = strprods.concat( ""+exp.next() );
        }
        
        //txtcodpro.setText(strprods);
        
        parcial = Double.parseDouble(txtcuenta.getText());
        
        tiva = parcial * iva;
        total = tiva + parcial;
        
        txtneto.setText(""+parcial);
        txtiva.setText(""+tiva);
        txttotal.setText(""+total);
        
        newsale.add(txtnfact.getText());
        newsale.add(txtcliente.getText());
        newsale.add(fecha.getDate());
        newsale.add(fecha.getHour());
        newsale.add(strprods);//prods
        newsale.add(total);
        newsale.add(0);
        newsale.add(txtcajero.getText());
        
        
        exe.SaveToBD( data.ArrayToBD( newsale ) );/**/
        
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getLocalizedMessage(), "POS Facturar",0);
        }
        
    }//GEN-LAST:event_Facturar_ActionPerformed

    private void txtcodproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodproActionPerformed
        // TODO add your handling code here:
        
        /*if ( this.hasFocus() ){
            añadir = "codpro";
        }*/
        
    }//GEN-LAST:event_txtcodproActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
        
        /* if ( this.hasFocus() ){
            añadir = "cant";
        }*/
        
    }//GEN-LAST:event_txtcantActionPerformed

    private void txtcajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcajeroActionPerformed

    private void opcprodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcprodItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_opcprodItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir_;
    private javax.swing.JButton Buscar_;
    private javax.swing.JButton Cuadrar_;
    private javax.swing.JButton Facturar_;
    private javax.swing.JButton Quitar_;
    private javax.swing.JButton Retraer_;
    private javax.swing.JButton Salir_;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton opccliente;
    private javax.swing.ButtonGroup opcioncampobusqueda_;
    private javax.swing.JRadioButton opcprod;
    private javax.swing.JTable tblcnst;
    private javax.swing.JTextField txtcajero;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodpro;
    private javax.swing.JTextArea txtcuenta;
    private javax.swing.JTextField txtdescprod;
    private javax.swing.JTextField txtfch;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtneto;
    private javax.swing.JTextField txtnfact;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
