
//code

package Vista;

import Modelo.ClasePrincipal;

import Controlador.CtrData;
import Modelo.MdlData;
//import Controlador.Fechas;
import java.util.ArrayList;//Maneja el ArrayList
import javax.swing.JOptionPane;
import javax.swing.table.*;


/**
 *
 * @author Miguel
 */
public class Inventarios extends javax.swing.JInternalFrame {
    
    String mitabla = "proveedores";
    DefaultTableModel dtm = new DefaultTableModel();
    Object obs;

    /**
     * Creates new form Clientes
     */
    public Inventarios() {
        initComponents();
        String[] campos = {"Codigo","Identificacion","Tipo","Razón Social","Direccion","Contacto","Email"};
        dtm.setColumnIdentifiers(campos);
        tblprov.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbtid = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        txttl = new javax.swing.JTextField();
        txtmil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Añadir_ = new javax.swing.JButton();
        Modificar_ = new javax.swing.JButton();
        Eliminar_ = new javax.swing.JButton();
        LimpiarPantalla_ = new javax.swing.JButton();
        Buscar_ = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprov = new javax.swing.JTable();
        lblcodprov = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Gestion Proveedores");

        jLabel1.setText("Identificacion (Id.): ");

        cmbtid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C.C.", "NIT", "RUT", "NIF" }));

        jLabel2.setText("Tipo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("e-mail:");

        Añadir_.setText("Ingresar");
        Añadir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir_ActionPerformed(evt);
            }
        });

        Modificar_.setText("Modificar");
        Modificar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_ActionPerformed(evt);
            }
        });

        Eliminar_.setText("Eliminar");
        Eliminar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ActionPerformed(evt);
            }
        });

        LimpiarPantalla_.setText("Limpiar");
        LimpiarPantalla_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarPantalla_ActionPerformed(evt);
            }
        });

        Buscar_.setText("Buscar");
        Buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ActionPerformed(evt);
            }
        });

        tblprov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblprov.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblprov);

        lblcodprov.setText("Defines Codigo?");

        txtcod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcodFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtdir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid)
                                    .addComponent(txtnm)
                                    .addComponent(txtmil))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbtid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(lblcodprov)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Añadir_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Modificar_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LimpiarPantalla_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcodprov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir_)
                    .addComponent(Modificar_)
                    .addComponent(Eliminar_)
                    .addComponent(LimpiarPantalla_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar_)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void LimpiarPantalla(){
        txtcod.setText("");
        txtid.setText("");
        cmbtid.setSelectedIndex(0);
        txtnm.setText("");
        txtdir.setText("");
        txttl.setText("");
        txtmil.setText("");
        try{
            for( int i=0; i<tblprov.getRowCount(); i++ ){
                dtm.removeRow(i);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getLocalizedMessage(), title, 0);
        }
    }
    
    public void miBusca(){
        CtrData data = new CtrData(mitabla);
        MdlData exe = new MdlData();
        
        try{
            String camp = "codprov";
            
            exe.Search(data.ExtWhere( camp, ""+obs ) );
            
            if(!exe.getResults().isEmpty()){
                dtm.addRow(exe.getResults().toArray());
            }
            
            txtcod.setText(""+exe.getResults().toArray()[0]);
            txtid.setText(""+exe.getResults().toArray()[1]);
            cmbtid.setSelectedItem(""+exe.getResults().toArray()[2]);
            txtnm.setText(""+exe.getResults().toArray()[3]);
            txtdir.setText(""+exe.getResults().toArray()[4]);
            txttl.setText(""+exe.getResults().toArray()[5]);
            txtmil.setText(""+exe.getResults().toArray()[6]);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getLocalizedMessage(), title,0);
        }
        exe = null;
        data = null;
    }
    
    
    private void Añadir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir_ActionPerformed
        // TODO add your handling code here:
        
        MdlData exe = new MdlData();
        CtrData data = new CtrData(mitabla);
        
        String codprov;
        
        ArrayList<Object> newreg = new ArrayList<>();
        
        if( "".equals(txtcod.getText()) ){
            codprov = txtid.getText();
        }
        else{
            codprov = txtcod.getText();
        }
        
        newreg.add(codprov);
        newreg.add(txtid.getText());
        newreg.add(cmbtid.getSelectedItem());
        newreg.add(txtnm.getText());
        newreg.add(txtdir.getText());
        newreg.add(txttl.getText());
        newreg.add(txtmil.getText());
        
        exe.SaveToBD(data.ArrayToBD(newreg));
        
        LimpiarPantalla();
        
        exe = null;
        data = null;
        
    }//GEN-LAST:event_Añadir_ActionPerformed

    private void txtcodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodFocusGained
        // TODO add your handling code here:
        
        lblcodprov.setText(lblcodprov.getText()+" \n Por defecto es Id.");
        
    }//GEN-LAST:event_txtcodFocusGained

    private void Buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ActionPerformed
        // TODO add your handling code here:
        
        if( !"".equals(txtsearch.getText()) ){
            this.obs = txtsearch.getText();
        }
        
        miBusca();
        
    }//GEN-LAST:event_Buscar_ActionPerformed

    private void Modificar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_ActionPerformed
        // TODO add your handling code here:
        
        CtrData data = new CtrData(mitabla);
        MdlData exe = new MdlData();
        
        String camps[] = {"codprov","idprov","idtipo","nombre","direccion","telefono","mail"};
        
        ArrayList<Object> newdata = new ArrayList<>();
        
        try{
            newdata.add(txtcod.getText());
            newdata.add(txtid.getText());
            newdata.add(cmbtid.getSelectedItem());
            newdata.add(txtnm.getText());
            newdata.add(txtdir.getText());
            newdata.add(txttl.getText());
            newdata.add(txtmil.getText());

            exe.Update(data.ChangeReg( "codprov", ""+obs, newdata, camps ));
            
            LimpiarPantalla();
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getLocalizedMessage(), "GUsers Modificar", 0);
        }
        
        exe = null;
        data = null;
        
    }//GEN-LAST:event_Modificar_ActionPerformed

    private void LimpiarPantalla_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarPantalla_ActionPerformed
        // TODO add your handling code here:
        
        LimpiarPantalla();
        
    }//GEN-LAST:event_LimpiarPantalla_ActionPerformed

    private void Eliminar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ActionPerformed
        // TODO add your handling code here:
        
        
        MdlData exe = new MdlData();
        CtrData data = new CtrData(mitabla);
        
        exe.Delete(data.EraseIt("iduser", ""+obs));
        
        LimpiarPantalla();
        
        exe = null;
        data = null;
                
    }//GEN-LAST:event_Eliminar_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir_;
    private javax.swing.JButton Buscar_;
    private javax.swing.JButton Eliminar_;
    private javax.swing.JButton LimpiarPantalla_;
    private javax.swing.JButton Modificar_;
    private javax.swing.JComboBox cmbtid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblcodprov;
    private javax.swing.JTable tblprov;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmil;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttl;
    // End of variables declaration//GEN-END:variables
}
