
//code

package Vista;

import Modelo.ClasePrincipal;

import Controlador.CtrData;
import Modelo.MdlData;
import Controlador.Fechas;
import java.util.ArrayList;//Maneja el ArrayList
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author ADSI38
 */
public class Pagos extends javax.swing.JInternalFrame {
    
    String mitabla = "productos";
    
    DefaultTableModel dtm = new DefaultTableModel();
    
    Object obs;
    
    /**
     * Creates new form Clientes
     */
    public Pagos() {
        initComponents();
        String[] hr = {"Código","Proveedor","Descripcion","Inventario","Fecha Surtido","Hora","Costo Und","Precio Venta"};
        dtm.setColumnIdentifiers(hr);
        tblprods.setModel(dtm);
        lblprov.setVisible(false);
        txtprov.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        txtcodpro = new javax.swing.JTextField();
        txtcantpro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AgregarRegistro_ = new javax.swing.JButton();
        Modificar_ = new javax.swing.JButton();
        Eliminar_ = new javax.swing.JButton();
        LimpiarPantalla_ = new javax.swing.JButton();
        Buscar_ = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprods = new javax.swing.JTable();
        txtcostund = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescpro = new javax.swing.JTextArea();
        txtprec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblprov = new javax.swing.JLabel();
        txtprov = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Gestion Productos");
        setName("GClientes"); // NOI18N

        jLabel4.setText("Código:");

        jLabel5.setText("Descripcion:");

        jLabel6.setText("Cantidad:");

        AgregarRegistro_.setText("Ingresar");
        AgregarRegistro_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRegistro_ActionPerformed(evt);
            }
        });

        Modificar_.setText("Modificar");
        Modificar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_ActionPerformed(evt);
            }
        });

        Eliminar_.setText("Eliminar");
        Eliminar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ActionPerformed(evt);
            }
        });

        LimpiarPantalla_.setText("Limpiar");
        LimpiarPantalla_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarPantalla_ActionPerformed(evt);
            }
        });

        Buscar_.setText("Buscar");
        Buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ActionPerformed(evt);
            }
        });

        tblprods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblprods.getTableHeader().setReorderingAllowed(false);
        tblprods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprodsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblprods);

        jLabel7.setText("Costo Unitario:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/GProductos.png"))); // NOI18N

        txtdescpro.setColumns(1);
        txtdescpro.setRows(2);
        jScrollPane2.setViewportView(txtdescpro);

        jLabel8.setText("Precio de Venta:");

        lblprov.setText("Codigo de Proveedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcantpro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcostund, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblprov)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtprov, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtprec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(AgregarRegistro_)
                        .addGap(18, 18, 18)
                        .addComponent(Modificar_)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar_)
                        .addGap(18, 18, 18)
                        .addComponent(LimpiarPantalla_)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcantpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtcostund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblprov)
                                .addGap(6, 6, 6)
                                .addComponent(txtprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(txtprec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Buscar_))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar_)
                    .addComponent(AgregarRegistro_)
                    .addComponent(Eliminar_)
                    .addComponent(LimpiarPantalla_)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LimpiarPantalla(){
            txtcodpro.setText("");
            txtdescpro.setText("");
            txtcantpro.setText("");
            txtcostund.setText("");
            txtprec.setText("");
        try{
            for( int i=0; i<tblprods.getRowCount(); i++ ){
                dtm.removeRow(i);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getLocalizedMessage(), title, 0);
        }
    }
    
    private void AgregarRegistro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRegistro_ActionPerformed
        // TODO add your handling code here:
        
        MdlData exe = new MdlData();
        CtrData data = new CtrData(mitabla);
        Fechas fecha = new Fechas();
        
        String codprov = null;
        
        int yn = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(rootPane, "¿Asignas un Proveedor?", "Nuevo Producto", yn);
        if( yn == JOptionPane.YES_OPTION ){
            codprov = JOptionPane.showInputDialog(rootPane, "Codigo Proveedor: ", "Proveedor", 3);
        }
        if( yn == JOptionPane.NO_OPTION ){
            remove(yn);
            codprov = null;
        }
        
        ArrayList<Object> newreg = new ArrayList<>();
        
        newreg.add(txtcodpro.getText());
        newreg.add(codprov);
        newreg.add(txtdescpro.getText());
        newreg.add(txtcantpro.getText());
        newreg.add(fecha.getDate());
        newreg.add(fecha.getHour());
        newreg.add(txtcostund.getText());
        newreg.add(txtprec.getText());
        
        exe.SaveToBD(data.ArrayToBD(newreg));
        
        LimpiarPantalla();
        
        
        
    }//GEN-LAST:event_AgregarRegistro_ActionPerformed

    private void Modificar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_ActionPerformed
        // TODO add your handling code here:
        
        CtrData data = new CtrData(mitabla);
        MdlData exe = new MdlData();
        
        String camps[] = {"codpro","codprov","descpro","inv","costound","prevenund"};
        
        ArrayList<Object> newdata = new ArrayList<>();
        
        try{
            newdata.add(txtcodpro.getText());
            newdata.add(txtprov.getText());
            newdata.add(txtdescpro.getText());
            newdata.add(txtcantpro.getText());
            newdata.add(txtcostund.getText());
            newdata.add(txtprec.getText());

            exe.Update(data.ChangeReg( "codpro", ""+obs, newdata, camps ));

            lblprov.setVisible(false);
            txtprov.setVisible(false);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getLocalizedMessage(), "GUsers Modificar", 0);
        }
        
        
        
    }//GEN-LAST:event_Modificar_ActionPerformed

    private void Buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ActionPerformed
        // TODO add your handling code here:
        
        if( !"".equals(txtsearch.getText()) ){
            this.obs = txtsearch.getText();
        }

        CtrData data = new CtrData(mitabla);
        MdlData exe = new MdlData();
        
        try{
            String camp = "codpro";
            exe.Search(data.ExtWhere(camp, ""+obs ) );
            
            if(!exe.getResults().isEmpty()){
                dtm.addRow( exe.getResults().toArray() );
            }
            
            txtcodpro.setText(""+exe.getResults().toArray()[0]);
            txtdescpro.setText(""+exe.getResults().toArray()[2]);
            txtcantpro.setText(""+exe.getResults().toArray()[3]);
            txtcostund.setText(""+exe.getResults().toArray()[6]);
            txtprec.setText(""+exe.getResults().toArray()[7]);
            
            lblprov.setVisible(true);
            txtprov.setVisible(true);
            txtprov.setText(""+exe.getResults().toArray()[1]);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Error: \n"+ex.getLocalizedMessage(), "GClientes",0);
        }
        
        
        
    }//GEN-LAST:event_Buscar_ActionPerformed

    private void Eliminar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ActionPerformed
        // TODO add your handling code here:
        
        MdlData exe = new MdlData();
        CtrData data = new CtrData(mitabla);
        
        exe.Delete(data.EraseIt("iduser", ""+obs));
        
        LimpiarPantalla();
        
        
    }//GEN-LAST:event_Eliminar_ActionPerformed

    private void LimpiarPantalla_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarPantalla_ActionPerformed
        // TODO add your handling code here:
        
        LimpiarPantalla();
        
    }//GEN-LAST:event_LimpiarPantalla_ActionPerformed

    private void tblprodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprodsMouseClicked
        // TODO add your handling code here:
        
        int fila = tblprods.rowAtPoint(evt.getPoint());
        int col = tblprods.columnAtPoint(evt.getPoint());
        if( fila > -1 && col > -1 ){
            this.obs = dtm.getValueAt(fila, 1);
        }
        
        //dtm.getColumnName(col);
        
    }//GEN-LAST:event_tblprodsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarRegistro_;
    private javax.swing.JButton Buscar_;
    private javax.swing.JButton Eliminar_;
    private javax.swing.JButton LimpiarPantalla_;
    private javax.swing.JButton Modificar_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblprov;
    private javax.swing.JTable tblprods;
    private javax.swing.JTextField txtcantpro;
    private javax.swing.JTextField txtcodpro;
    private javax.swing.JTextField txtcostund;
    private javax.swing.JTextArea txtdescpro;
    private javax.swing.JTextField txtprec;
    private javax.swing.JTextField txtprov;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
